# Site settings
title: Fantasy
username: guochy2012
email: guochy2012@gmail.com
description: "Succinctly"
url: "http://guochy2012.github.io"

markdown: kramdown
permalink: /:title

comments :
    provider : duoshuo
    duoshuo : 
      short_name : guochy2012

sass:
  sass_dir: public/css
  style: :compressed
